.docker:
  image: golang:alpine
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: '1'
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: '20.10.16'
    DAGGER_CLOUD_TOKEN: $DAGGER_CLOUD_TOKEN
.dagger:
  extends: [.docker]
  before_script:
    - apk add docker-cli curl
    - cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
build:
  extends: [.dagger]
  script:
    # test speed to pull engine
    stage: pull_engine
    - dagger core

    # test speed to call functions the first time
    stage: first_functions
    - dagger functions 

    # test speed to call functions the second time
    stage: second_functions
    - dagger functions 

    # test speed to call ci
    stage: ci_run
    - dagger call ci 

    # test speed to call ci and see cache
    stage: ci_cache
    - dagger -vvv call ci 