pipeline:
  identifier: BuildSnippetbox
  name: Build snippetbox singly
  orgIdentifier: default
  projectIdentifier: snippetbox
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1726074577341
        repoName: levlaz/snippetbox
  stages:
    - stage:
        identifier: build
        name: build
        variables:
          - name: DAGGER_CLOUD_TOKEN
            type: String
            description: Dagger Cloud Token
            value: <+secrets.getValue("DAGGER_CLOUD_TOKEN")>
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: daggerInstall
                  name: Install Dagger
                  spec:
                    command: curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
                  timeout: ""
                  type: Run
              - step:
                  identifier: daggerCall
                  name: Call Dagger Pipeline
                  spec:
                    command: dagger call ci
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
