name: dagger
on:
  push:
    branches: ['*']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: build release
      	uses: dagger/dagger-for-github@8.0.0
	with:
		version: "latest"
		args: ci 
		cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
