name: dagger
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Dagger Image & Run Core
        uses: dagger/dagger-for-github@v6.15.1
        with:
          verb: core
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.15.1"
      - name: Run Functions First Time
        uses: dagger/dagger-for-github@v6.15.1
        with:
          verb: functions -q
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.15.1"
      - name: Run Functions Second Time
        uses: dagger/dagger-for-github@v6.15.1
        with:
          verb: functions -q
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.15.1"
      - name: Run CI pipeline
        uses: dagger/dagger-for-github@v6.15.1
        with:
          module: .
          call: ci
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.15.1"